services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ./config:/app/config:ro
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - backend

  redis:
    image: redis:7.2-alpine
    command:
      - redis-server --requirepass ${REDIS_PASSWORD}
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - backend

volumes:
  redis_data:

networks:
  backend:
    driver: bridge